plugins {
    alias(libs.plugins.androidApplication)
    alias(libs.plugins.compose.compiler)
    alias(libs.plugins.ktlint)
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

android {
    namespace = "cc.ddsakura.modernapp001"
    compileSdk = 37

    defaultConfig {
        applicationId = "cc.ddsakura.modernapp001"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding = true
        compose = true
        buildConfig = true
    }
    // OFFICIAL (Android Studio / Gemini): generated by the "New > Journey Test"
    // wizard the first time a journey is created in Android Studio. Requires
    // android.experimental.testSuiteSupport=true in gradle.properties (also added
    // by the wizard) and runs journeys through Gemini, driven from the IDE.
    testOptions {
        suites {
            create("journeysTest") {
                assets {
                }
                targets {
                    create("default") {
                    }
                }
                useJunitEngine {
                    inputs += listOf(com.android.build.api.dsl.AgpTestSuiteInputParameters.TESTED_APKS)
                    includeEngines += listOf("journeys-test-engine")
                    enginesDependencies(libs.junit.platform.launcher)
                    enginesDependencies(libs.junit.platform.engine)
                    enginesDependencies(libs.journeys.junit.engine)
                }
                targetVariants += listOf("debug")
            }
        }
    }
}

// OFFICIAL (Android Studio / Gemini) fix-up: the journeys-test-engine's Robo
// crawler client (used by the testOptions.suites block above) is compiled for
// JDK 21 (class file version 65), but this project pins its Java toolchain to 17
// above, so the generated test task fails with UnsupportedClassVersionError unless
// it's forced onto a JDK 21 launcher. Matched by prefix/suffix (rather than the
// exact "testJourneysTestDefaultDebugTestSuite" task name) so this keeps applying
// if more targets or variants are added to the "journeysTest" suite later.
// A JDK 21 install isn't required on the machine running this: the
// foojay-resolver-convention plugin (settings.gradle.kts) auto-provisions any
// toolchain version Gradle can't find locally.
tasks.withType<Test>()
    .matching { it.name.startsWith("testJourneysTest") && it.name.endsWith("TestSuite") }
    .configureEach {
        javaLauncher.set(
            javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(21))
            }
        )
    }

dependencies {
    coreLibraryDesugaring(libs.desugar.jdk.libs)

    implementation(libs.webkit)
    implementation(libs.core.ktx)
    implementation(libs.appcompat)
    implementation(libs.fragment.ktx)
    implementation(libs.constraintlayout)
    implementation(libs.legacy.support.v4)

    implementation(libs.retrofit)

    implementation(libs.activity.compose)
    implementation(libs.navigation.compose)
    implementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)

    implementation(libs.androidx.compose.material3)
    implementation(libs.androidx.compose.material.icons.extended)
    implementation(libs.androidx.compose.ui.tooling.preview)
    debugImplementation(libs.androidx.compose.ui.tooling)

    implementation(libs.glance.appwidget)
    implementation(libs.navigation.fragment.ktx)
    implementation(libs.navigation.ui.ktx)

    testImplementation(libs.junit)
    androidTestImplementation(libs.ext.junit)
    androidTestImplementation(libs.espresso.core)
    androidTestImplementation(libs.androidx.compose.ui.test.junit4)

    debugImplementation(libs.androidx.glance.preview)
    debugImplementation(libs.androidx.glance.appwidget.preview)
    debugImplementation(libs.androidx.ui.test.manifest)
}
