## 1
name: Test and deploy

## Actions that will be executed when you push code currently none
on:
  push:

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Unit tests
        run: ./gradlew test

  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Android tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedAndroidTest

  build:
    needs: [ unit_tests, android_tests ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - uses: actions/upload-artifact@master
        with:
          name: debug.apk
          path: app/build/outputs/apk/release/app-release-unsigned.apk
